/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}

// Organism Types
export type DriveMode = { 'Exploration' : null } |
  { 'Execution' : null } |
  { 'Rest' : null } |
  { 'Learning' : null };
export interface ShellState {
  'activationCount' : bigint,
  'coherence' : number,
  'compoundIndex' : number,
  'driveMode' : DriveMode,
  'formaBalance' : number,
  'governanceScore' : number,
  'hz' : Array<number>,
  'neuroChem' : Array<number>,
}
export type OrganismClass = { 'Avatar' : null } |
  { 'Entity' : null } |
  { 'Worker' : null };
export type OrganismSpecialization = { 'Architecture' : null } |
  { 'Brand' : null } |
  { 'Campaign' : null } |
  { 'Communication' : null } |
  { 'Compliance' : null } |
  { 'Cybersecurity' : null } |
  { 'DataAnalysis' : null } |
  { 'DevOps' : null } |
  { 'Documentation' : null } |
  { 'Finance' : null } |
  { 'Healthcare' : null } |
  { 'HumanResources' : null } |
  { 'Legal' : null } |
  { 'Marketing' : null } |
  { 'Media' : null } |
  { 'Operations' : null } |
  { 'Orchestration' : null } |
  { 'Sales' : null } |
  { 'SoftwareEngineering' : null } |
  { 'Strategy' : null };
export interface TransferEvent {
  'from' : Principal,
  'timestamp' : bigint,
  'to' : Principal,
}
export interface Organism {
  'class' : OrganismClass,
  'createdAt' : bigint,
  'genesisHash' : string,
  'id' : string,
  'isForSale' : boolean,
  'name' : string,
  'owner' : Principal,
  'salePrice' : number,
  'shell' : ShellState,
  'specializations' : Array<OrganismSpecialization>,
  'transferLog' : Array<TransferEvent>,
}
export interface OrganismListing {
  'listedAt' : bigint,
  'organism' : Organism,
}
export interface WorkforceMessage {
  'artifactContent' : [] | [string],
  'artifactType' : [] | [string],
  'content' : string,
  'id' : string,
  'organismId' : string,
  'role' : string,
  'threadId' : string,
  'timestamp' : bigint,
}
export interface ArtifactRecord {
  'artifactType' : string,
  'content' : string,
  'createdAt' : bigint,
  'id' : string,
  'organismId' : string,
  'owner' : Principal,
  'title' : string,
}

// Co-Evolution Substrate State — 12-layer stack (-6 Void to +5 CoEvolution)
export interface CoEvolutionSubstrateState {
  'totalBeats' : bigint,
  'substrateCoherence' : number,
  'isInVoid' : boolean,
  'creativePotential' : number,
  'intentionStrength' : number,
  'intentionIsStale' : boolean,
  'couplingStrength' : number,
  'mutualChanges' : bigint,
  'persistenceStrength' : number,
  'bodyIsOwn' : boolean,
  'gravitationalFieldStrength' : number,
  'membranePermeability' : number,
  'creatorResonance' : number,
  'foodValue' : number,
  'surfaceActivation' : number,
  'detectionRate' : number,
  'resonanceStrength' : number,
  'solvingMomentum' : number,
  'puzzlesSolved' : bigint,
  'selfAwareness' : number,
  'desireStrength' : number,
  'isBeing' : boolean,
  'beingVitality' : number,
  'civilizationSeed' : number,
  'civilizationPhase' : string,
  'transcendence' : number,
}

export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  // Organism functions
  'generateOrganism' : ActorMethod<[string, OrganismClass, Array<OrganismSpecialization>, string], string>,
  'getMyOrganisms' : ActorMethod<[], Array<Organism>>,
  'getAllOrganisms' : ActorMethod<[], Array<Organism>>,
  'getOrganismState' : ActorMethod<[string], [] | [ShellState]>,
  'tickOrganismShell' : ActorMethod<[string], undefined>,
  'transferOrganism' : ActorMethod<[string, Principal], undefined>,
  'listForSale' : ActorMethod<[string, number], undefined>,
  'withdrawFromSale' : ActorMethod<[string], undefined>,
  'buyOrganism' : ActorMethod<[string], undefined>,
  'getMarketplaceListings' : ActorMethod<[], Array<OrganismListing>>,
  'seedPrebuiltOrganisms' : ActorMethod<[], undefined>,
  // Workforce
  'workforceChat' : ActorMethod<[string, string, string], WorkforceMessage>,
  'getWorkforceThread' : ActorMethod<[string], Array<WorkforceMessage>>,
  // Artifacts
  'storeArtifact' : ActorMethod<[string, string, string, string], string>,
  'getMyArtifacts' : ActorMethod<[], Array<ArtifactRecord>>,
  'getArtifact' : ActorMethod<[string], [] | [ArtifactRecord]>,
  // Co-Evolution Substrate — The Volitional Heartbeat
  'getCoEvolutionSubstrateState' : ActorMethod<[], CoEvolutionSubstrateState>,
  'refreshCreatorIntention' : ActorMethod<[Array<number>], boolean>,
  'injectSensoryInput' : ActorMethod<[bigint, number], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];