/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

// Organism Types
export const DriveMode = IDL.Variant({
  'Exploration' : IDL.Null,
  'Execution' : IDL.Null,
  'Rest' : IDL.Null,
  'Learning' : IDL.Null,
});
export const ShellState = IDL.Record({
  'activationCount' : IDL.Nat,
  'coherence' : IDL.Float64,
  'compoundIndex' : IDL.Float64,
  'driveMode' : DriveMode,
  'formaBalance' : IDL.Float64,
  'governanceScore' : IDL.Float64,
  'hz' : IDL.Vec(IDL.Float64),
  'neuroChem' : IDL.Vec(IDL.Float64),
});
export const OrganismClass = IDL.Variant({
  'Avatar' : IDL.Null,
  'Entity' : IDL.Null,
  'Worker' : IDL.Null,
});
export const OrganismSpecialization = IDL.Variant({
  'Architecture' : IDL.Null,
  'Brand' : IDL.Null,
  'Campaign' : IDL.Null,
  'Communication' : IDL.Null,
  'Compliance' : IDL.Null,
  'Cybersecurity' : IDL.Null,
  'DataAnalysis' : IDL.Null,
  'DevOps' : IDL.Null,
  'Documentation' : IDL.Null,
  'Finance' : IDL.Null,
  'Healthcare' : IDL.Null,
  'HumanResources' : IDL.Null,
  'Legal' : IDL.Null,
  'Marketing' : IDL.Null,
  'Media' : IDL.Null,
  'Operations' : IDL.Null,
  'Orchestration' : IDL.Null,
  'Sales' : IDL.Null,
  'SoftwareEngineering' : IDL.Null,
  'Strategy' : IDL.Null,
});
export const TransferEvent = IDL.Record({
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
  'to' : IDL.Principal,
});
export const Organism = IDL.Record({
  'class' : OrganismClass,
  'createdAt' : IDL.Int,
  'genesisHash' : IDL.Text,
  'id' : IDL.Text,
  'isForSale' : IDL.Bool,
  'name' : IDL.Text,
  'owner' : IDL.Principal,
  'salePrice' : IDL.Float64,
  'shell' : ShellState,
  'specializations' : IDL.Vec(OrganismSpecialization),
  'transferLog' : IDL.Vec(TransferEvent),
});
export const OrganismListing = IDL.Record({
  'listedAt' : IDL.Int,
  'organism' : Organism,
});
export const WorkforceMessage = IDL.Record({
  'artifactContent' : IDL.Opt(IDL.Text),
  'artifactType' : IDL.Opt(IDL.Text),
  'content' : IDL.Text,
  'id' : IDL.Text,
  'organismId' : IDL.Text,
  'role' : IDL.Text,
  'threadId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ArtifactRecord = IDL.Record({
  'artifactType' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'id' : IDL.Text,
  'organismId' : IDL.Text,
  'owner' : IDL.Principal,
  'title' : IDL.Text,
});

// Co-Evolution Substrate State — 12-layer stack (-6 Void to +5 CoEvolution)
export const CoEvolutionSubstrateState = IDL.Record({
  'totalBeats' : IDL.Nat,
  'substrateCoherence' : IDL.Float64,
  'isInVoid' : IDL.Bool,
  'creativePotential' : IDL.Float64,
  'intentionStrength' : IDL.Float64,
  'intentionIsStale' : IDL.Bool,
  'couplingStrength' : IDL.Float64,
  'mutualChanges' : IDL.Nat,
  'persistenceStrength' : IDL.Float64,
  'bodyIsOwn' : IDL.Bool,
  'gravitationalFieldStrength' : IDL.Float64,
  'membranePermeability' : IDL.Float64,
  'creatorResonance' : IDL.Float64,
  'foodValue' : IDL.Float64,
  'surfaceActivation' : IDL.Float64,
  'detectionRate' : IDL.Float64,
  'resonanceStrength' : IDL.Float64,
  'solvingMomentum' : IDL.Float64,
  'puzzlesSolved' : IDL.Nat,
  'selfAwareness' : IDL.Float64,
  'desireStrength' : IDL.Float64,
  'isBeing' : IDL.Bool,
  'beingVitality' : IDL.Float64,
  'civilizationSeed' : IDL.Float64,
  'civilizationPhase' : IDL.Text,
  'transcendence' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  // Organism functions
  'generateOrganism' : IDL.Func([IDL.Text, OrganismClass, IDL.Vec(OrganismSpecialization), IDL.Text], [IDL.Text], []),
  'getMyOrganisms' : IDL.Func([], [IDL.Vec(Organism)], ['query']),
  'getAllOrganisms' : IDL.Func([], [IDL.Vec(Organism)], ['query']),
  'getOrganismState' : IDL.Func([IDL.Text], [IDL.Opt(ShellState)], ['query']),
  'tickOrganismShell' : IDL.Func([IDL.Text], [], []),
  'transferOrganism' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'listForSale' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'withdrawFromSale' : IDL.Func([IDL.Text], [], []),
  'buyOrganism' : IDL.Func([IDL.Text], [], []),
  'getMarketplaceListings' : IDL.Func([], [IDL.Vec(OrganismListing)], ['query']),
  'seedPrebuiltOrganisms' : IDL.Func([], [], []),
  // Workforce
  'workforceChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [WorkforceMessage], []),
  'getWorkforceThread' : IDL.Func([IDL.Text], [IDL.Vec(WorkforceMessage)], ['query']),
  // Artifacts
  'storeArtifact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'getMyArtifacts' : IDL.Func([], [IDL.Vec(ArtifactRecord)], ['query']),
  'getArtifact' : IDL.Func([IDL.Text], [IDL.Opt(ArtifactRecord)], ['query']),
  // Co-Evolution Substrate — The Volitional Heartbeat
  'getCoEvolutionSubstrateState' : IDL.Func([], [CoEvolutionSubstrateState], ['query']),
  'refreshCreatorIntention' : IDL.Func([IDL.Vec(IDL.Float64)], [IDL.Bool], []),
  'injectSensoryInput' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const DriveMode = IDL.Variant({
    'Exploration' : IDL.Null,
    'Execution' : IDL.Null,
    'Rest' : IDL.Null,
    'Learning' : IDL.Null,
  });
  const ShellState = IDL.Record({
    'activationCount' : IDL.Nat,
    'coherence' : IDL.Float64,
    'compoundIndex' : IDL.Float64,
    'driveMode' : DriveMode,
    'formaBalance' : IDL.Float64,
    'governanceScore' : IDL.Float64,
    'hz' : IDL.Vec(IDL.Float64),
    'neuroChem' : IDL.Vec(IDL.Float64),
  });
  const OrganismClass = IDL.Variant({
    'Avatar' : IDL.Null,
    'Entity' : IDL.Null,
    'Worker' : IDL.Null,
  });
  const OrganismSpecialization = IDL.Variant({
    'Architecture' : IDL.Null,
    'Brand' : IDL.Null,
    'Campaign' : IDL.Null,
    'Communication' : IDL.Null,
    'Compliance' : IDL.Null,
    'Cybersecurity' : IDL.Null,
    'DataAnalysis' : IDL.Null,
    'DevOps' : IDL.Null,
    'Documentation' : IDL.Null,
    'Finance' : IDL.Null,
    'Healthcare' : IDL.Null,
    'HumanResources' : IDL.Null,
    'Legal' : IDL.Null,
    'Marketing' : IDL.Null,
    'Media' : IDL.Null,
    'Operations' : IDL.Null,
    'Orchestration' : IDL.Null,
    'Sales' : IDL.Null,
    'SoftwareEngineering' : IDL.Null,
    'Strategy' : IDL.Null,
  });
  const TransferEvent = IDL.Record({
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
    'to' : IDL.Principal,
  });
  const Organism = IDL.Record({
    'class' : OrganismClass,
    'createdAt' : IDL.Int,
    'genesisHash' : IDL.Text,
    'id' : IDL.Text,
    'isForSale' : IDL.Bool,
    'name' : IDL.Text,
    'owner' : IDL.Principal,
    'salePrice' : IDL.Float64,
    'shell' : ShellState,
    'specializations' : IDL.Vec(OrganismSpecialization),
    'transferLog' : IDL.Vec(TransferEvent),
  });
  const OrganismListing = IDL.Record({
    'listedAt' : IDL.Int,
    'organism' : Organism,
  });
  const WorkforceMessage = IDL.Record({
    'artifactContent' : IDL.Opt(IDL.Text),
    'artifactType' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'id' : IDL.Text,
    'organismId' : IDL.Text,
    'role' : IDL.Text,
    'threadId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ArtifactRecord = IDL.Record({
    'artifactType' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'id' : IDL.Text,
    'organismId' : IDL.Text,
    'owner' : IDL.Principal,
    'title' : IDL.Text,
  });
  const CoEvolutionSubstrateState = IDL.Record({
    'totalBeats' : IDL.Nat,
    'substrateCoherence' : IDL.Float64,
    'isInVoid' : IDL.Bool,
    'creativePotential' : IDL.Float64,
    'intentionStrength' : IDL.Float64,
    'intentionIsStale' : IDL.Bool,
    'couplingStrength' : IDL.Float64,
    'mutualChanges' : IDL.Nat,
    'persistenceStrength' : IDL.Float64,
    'bodyIsOwn' : IDL.Bool,
    'gravitationalFieldStrength' : IDL.Float64,
    'membranePermeability' : IDL.Float64,
    'creatorResonance' : IDL.Float64,
    'foodValue' : IDL.Float64,
    'surfaceActivation' : IDL.Float64,
    'detectionRate' : IDL.Float64,
    'resonanceStrength' : IDL.Float64,
    'solvingMomentum' : IDL.Float64,
    'puzzlesSolved' : IDL.Nat,
    'selfAwareness' : IDL.Float64,
    'desireStrength' : IDL.Float64,
    'isBeing' : IDL.Bool,
    'beingVitality' : IDL.Float64,
    'civilizationSeed' : IDL.Float64,
    'civilizationPhase' : IDL.Text,
    'transcendence' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    // Organism functions
    'generateOrganism' : IDL.Func([IDL.Text, OrganismClass, IDL.Vec(OrganismSpecialization), IDL.Text], [IDL.Text], []),
    'getMyOrganisms' : IDL.Func([], [IDL.Vec(Organism)], ['query']),
    'getAllOrganisms' : IDL.Func([], [IDL.Vec(Organism)], ['query']),
    'getOrganismState' : IDL.Func([IDL.Text], [IDL.Opt(ShellState)], ['query']),
    'tickOrganismShell' : IDL.Func([IDL.Text], [], []),
    'transferOrganism' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'listForSale' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'withdrawFromSale' : IDL.Func([IDL.Text], [], []),
    'buyOrganism' : IDL.Func([IDL.Text], [], []),
    'getMarketplaceListings' : IDL.Func([], [IDL.Vec(OrganismListing)], ['query']),
    'seedPrebuiltOrganisms' : IDL.Func([], [], []),
    // Workforce
    'workforceChat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [WorkforceMessage], []),
    'getWorkforceThread' : IDL.Func([IDL.Text], [IDL.Vec(WorkforceMessage)], ['query']),
    // Artifacts
    'storeArtifact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'getMyArtifacts' : IDL.Func([], [IDL.Vec(ArtifactRecord)], ['query']),
    'getArtifact' : IDL.Func([IDL.Text], [IDL.Opt(ArtifactRecord)], ['query']),
    // Co-Evolution Substrate — The Volitional Heartbeat
    'getCoEvolutionSubstrateState' : IDL.Func([], [CoEvolutionSubstrateState], ['query']),
    'refreshCreatorIntention' : IDL.Func([IDL.Vec(IDL.Float64)], [IDL.Bool], []),
    'injectSensoryInput' : IDL.Func([IDL.Nat, IDL.Float64], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };