#!/usr/bin/env python3
"""
Nova Economics — Token Economics and Usage Tracking
Nova by FreddyCreates — Pythonista iOS

Tracks:
- Tool usage and costs
- IP value accumulation
- Token economics
- Usage analytics
"""

import time
import math
from typing import Dict, List, Optional
from dataclasses import dataclass, field

# Import φ constants
try:
    from phi import PHI, PHI_INV, fib
except ImportError:
    PHI = 1.618033988749895
    PHI_INV = 0.618033988749895
    def fib(n):
        if n <= 1: return n
        a, b = 0, 1
        for _ in range(n - 1):
            a, b = b, a + b
        return b


@dataclass
class UsageRecord:
    """Record of a tool usage."""
    quad: str
    timestamp: float
    duration_ms: int
    quality: float
    ip_value: float
    tokens_used: int = 0
    success: bool = True


@dataclass
class TokenBalance:
    """Token balance for a user/session."""
    total_earned: float = 0.0
    total_spent: float = 0.0
    current_balance: float = 1000.0  # Starting balance
    
    @property
    def net_balance(self) -> float:
        return self.current_balance + self.total_earned - self.total_spent


class NovaEconomics:
    """
    Nova Economics — Token economics and usage tracking.
    
    Implements φ-weighted pricing and IP value accumulation.
    """
    
    # Token costs per category (base cost in tokens)
    BASE_COSTS = {
        'text': 1,
        'vision': 3,
        'audio': 5,
        'code': 2,
        'data': 2,
    }
    
    # IP value multipliers
    IP_MULTIPLIERS = {
        'text': 1.0,
        'vision': PHI,
        'audio': PHI,
        'code': PHI * PHI,  # φ² for code
        'data': PHI,
    }
    
    def __init__(self):
        self.usage_history: List[UsageRecord] = []
        self.balance = TokenBalance()
        self.session_start = time.time()
        self.total_ip_generated = 0.0
    
    def compute_cost(self, quad: str, category: str, 
                     duration_ms: int, quality: float) -> int:
        """
        Compute token cost for a tool usage.
        
        Cost = base_cost × φ^(duration_factor) × quality_factor
        """
        base = self.BASE_COSTS.get(category, 1)
        
        # Duration factor (longer = more expensive, but with diminishing returns)
        duration_factor = math.log(duration_ms / 1000 + 1) / math.log(PHI)
        
        # Quality factor (higher quality = slightly more expensive)
        quality_factor = 1 + quality * PHI_INV
        
        cost = int(base * (PHI ** duration_factor) * quality_factor)
        return max(1, cost)  # Minimum 1 token
    
    def compute_ip_value(self, quad: str, category: str,
                         duration_ms: int, quality: float) -> float:
        """
        Compute IP value generated by a tool usage.
        
        IP = quality × multiplier × φ × (1 / log(duration + 1))
        """
        multiplier = self.IP_MULTIPLIERS.get(category, 1.0)
        
        # Faster, higher quality = more IP value
        time_factor = 1 / math.log(duration_ms / 1000 + 2)
        
        ip_value = quality * multiplier * PHI * time_factor
        return ip_value
    
    def record_usage(self, quad: str, category: str,
                     duration_ms: int, quality: float,
                     success: bool = True) -> Dict:
        """
        Record a tool usage and update economics.
        
        Returns:
            Dict with cost, IP value, and balance info
        """
        # Compute cost and IP
        cost = self.compute_cost(quad, category, duration_ms, quality)
        ip_value = self.compute_ip_value(quad, category, duration_ms, quality) if success else 0
        
        # Create record
        record = UsageRecord(
            quad=quad,
            timestamp=time.time(),
            duration_ms=duration_ms,
            quality=quality,
            ip_value=ip_value,
            tokens_used=cost,
            success=success,
        )
        self.usage_history.append(record)
        
        # Update balance
        self.balance.total_spent += cost
        self.balance.total_earned += ip_value * 0.1  # 10% of IP as token reward
        self.total_ip_generated += ip_value
        
        return {
            'quad': quad,
            'category': category,
            'tokens_used': cost,
            'ip_generated': round(ip_value, 4),
            'tokens_earned': round(ip_value * 0.1, 4),
            'balance': round(self.balance.net_balance, 2),
            'success': success,
        }
    
    def get_balance(self) -> Dict:
        """Get current token balance."""
        return {
            'current_balance': round(self.balance.current_balance, 2),
            'total_earned': round(self.balance.total_earned, 2),
            'total_spent': round(self.balance.total_spent, 2),
            'net_balance': round(self.balance.net_balance, 2),
            'total_ip_generated': round(self.total_ip_generated, 4),
        }
    
    def get_usage_stats(self) -> Dict:
        """Get usage statistics."""
        if not self.usage_history:
            return {
                'total_calls': 0,
                'success_rate': 0.0,
                'avg_duration_ms': 0,
                'avg_quality': 0.0,
                'by_category': {},
            }
        
        total = len(self.usage_history)
        successes = sum(1 for r in self.usage_history if r.success)
        
        # By category
        by_category = {}
        for record in self.usage_history:
            cat = record.quad[:4]  # Approximate category from QUAD
            if cat not in by_category:
                by_category[cat] = {'calls': 0, 'ip': 0.0, 'tokens': 0}
            by_category[cat]['calls'] += 1
            by_category[cat]['ip'] += record.ip_value
            by_category[cat]['tokens'] += record.tokens_used
        
        return {
            'total_calls': total,
            'success_rate': round(successes / total, 4),
            'avg_duration_ms': int(sum(r.duration_ms for r in self.usage_history) / total),
            'avg_quality': round(sum(r.quality for r in self.usage_history) / total, 4),
            'by_quad': by_category,
            'session_duration_s': int(time.time() - self.session_start),
        }
    
    def get_pricing_table(self) -> Dict:
        """Get pricing table for all categories."""
        table = {}
        for category, base_cost in self.BASE_COSTS.items():
            table[category] = {
                'base_cost': base_cost,
                'ip_multiplier': round(self.IP_MULTIPLIERS.get(category, 1.0), 4),
                'example_costs': {
                    'fast_low_quality': self.compute_cost('XXXX', category, 100, 0.5),
                    'medium': self.compute_cost('XXXX', category, 1000, 0.7),
                    'slow_high_quality': self.compute_cost('XXXX', category, 5000, 0.95),
                },
            }
        return table
    
    def add_tokens(self, amount: float):
        """Add tokens to balance (purchase or reward)."""
        self.balance.current_balance += amount
    
    def status(self) -> Dict:
        """Get economics status."""
        return {
            'name': 'Nova Economics',
            'brand': 'Nova by FreddyCreates',
            'balance': self.get_balance(),
            'usage': self.get_usage_stats(),
            'pricing': self.get_pricing_table(),
            'phi': PHI,
        }


# ─── Global Economics Instance ───────────────────────────────────────────────
_economics = None

def get_economics() -> NovaEconomics:
    """Get or create the global economics instance."""
    global _economics
    if _economics is None:
        _economics = NovaEconomics()
    return _economics


# ─── Quick Access Functions ──────────────────────────────────────────────────
def record_usage(quad: str, category: str, duration_ms: int, 
                 quality: float, success: bool = True) -> Dict:
    """Record tool usage."""
    return get_economics().record_usage(quad, category, duration_ms, quality, success)

def get_balance() -> Dict:
    """Get token balance."""
    return get_economics().get_balance()

def get_usage_stats() -> Dict:
    """Get usage statistics."""
    return get_economics().get_usage_stats()


# ─── Self-Test ───────────────────────────────────────────────────────────────
if __name__ == '__main__':
    print("╔════════════════════════════════════════════════════════════════╗")
    print("║              Nova Economics — Self-Test                        ║")
    print("║              Nova by FreddyCreates                             ║")
    print("╚════════════════════════════════════════════════════════════════╝")
    print()
    
    econ = get_economics()
    
    print("─── INITIAL BALANCE ───")
    balance = econ.get_balance()
    print(f"Starting balance: {balance['current_balance']} tokens")
    print()
    
    print("─── PRICING TABLE ───")
    pricing = econ.get_pricing_table()
    for category, info in pricing.items():
        print(f"{category}: base={info['base_cost']}, multiplier={info['ip_multiplier']}")
    print()
    
    print("─── SIMULATING USAGE ───")
    # Simulate some tool usage
    usages = [
        ('SUMM', 'text', 500, 0.8),
        ('CLAS', 'vision', 1500, 0.9),
        ('TRNS', 'audio', 3000, 0.85),
        ('GENC', 'code', 2000, 0.95),
        ('ANLD', 'data', 1000, 0.75),
    ]
    
    for quad, category, duration, quality in usages:
        result = econ.record_usage(quad, category, duration, quality)
        print(f"[{quad}] Cost: {result['tokens_used']} tokens, IP: {result['ip_generated']}")
    print()
    
    print("─── FINAL BALANCE ───")
    balance = econ.get_balance()
    print(f"Net balance: {balance['net_balance']} tokens")
    print(f"Total IP generated: {balance['total_ip_generated']}")
    print()
    
    print("─── USAGE STATS ───")
    stats = econ.get_usage_stats()
    print(f"Total calls: {stats['total_calls']}")
    print(f"Success rate: {stats['success_rate']}")
    print(f"Avg quality: {stats['avg_quality']}")
    print()
    
    print("✓ Economics system ready.")
